/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApiResult = { 'ok' : Product } |
  { 'err' : string };
export type ApiResult_1 = { 'ok' : boolean } |
  { 'err' : string };
export type ApiResult_2 = { 'ok' : SaleRecord } |
  { 'err' : string };
export type ApiResult_3 = { 'ok' : PurchaseRecord } |
  { 'err' : string };
export interface CreateProductInput {
  'purchasePrice' : number,
  'lowStockThreshold' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'quantity' : bigint,
  'category' : string,
  'salePrice' : number,
}
export interface CreatePurchaseInput {
  'cost' : number,
  'supplierName' : string,
  'date' : Timestamp,
  'productId' : ProductId,
  'notes' : string,
  'quantity' : bigint,
}
export interface CreateSaleInput {
  'customerName' : string,
  'date' : Timestamp,
  'productId' : ProductId,
  'notes' : string,
  'quantitySold' : bigint,
  'salePrice' : number,
}
export interface InventoryStatus { 'isLowStock' : boolean, 'product' : Product }
export interface LoginInput { 'username' : string, 'password' : string }
export type LoginResult = { 'ok' : SessionToken } |
  { 'err' : string };
export interface Product {
  'id' : ProductId,
  'purchasePrice' : number,
  'lowStockThreshold' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'imageUrl' : string,
  'quantity' : bigint,
  'category' : string,
  'salePrice' : number,
}
export type ProductId = bigint;
export type PurchaseId = bigint;
export interface PurchaseRecord {
  'id' : PurchaseId,
  'cost' : number,
  'supplierName' : string,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'notes' : string,
  'quantity' : bigint,
}
export type SaleId = bigint;
export interface SaleRecord {
  'id' : SaleId,
  'customerName' : string,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'notes' : string,
  'quantitySold' : bigint,
  'salePrice' : number,
}
export type SessionToken = string;
export type Timestamp = bigint;
export interface UpdateProductInput {
  'id' : ProductId,
  'purchasePrice' : [] | [number],
  'lowStockThreshold' : [] | [bigint],
  'name' : [] | [string],
  'description' : [] | [string],
  'imageUrl' : [] | [string],
  'quantity' : [] | [bigint],
  'category' : [] | [string],
  'salePrice' : [] | [number],
}
export interface _SERVICE {
  'adminLogin' : ActorMethod<[LoginInput], LoginResult>,
  'adminLogout' : ActorMethod<[SessionToken], boolean>,
  'createProduct' : ActorMethod<[SessionToken, CreateProductInput], ApiResult>,
  'createPurchaseRecord' : ActorMethod<
    [SessionToken, CreatePurchaseInput],
    ApiResult_3
  >,
  'createSaleRecord' : ActorMethod<
    [SessionToken, CreateSaleInput],
    ApiResult_2
  >,
  'deleteProduct' : ActorMethod<[SessionToken, ProductId], ApiResult_1>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllPurchaseRecords' : ActorMethod<[SessionToken], Array<PurchaseRecord>>,
  'getAllSaleRecords' : ActorMethod<[SessionToken], Array<SaleRecord>>,
  'getInventoryStatus' : ActorMethod<[], Array<InventoryStatus>>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'isAdminAuthenticated' : ActorMethod<[SessionToken], boolean>,
  'updateLowStockThreshold' : ActorMethod<
    [SessionToken, ProductId, bigint],
    ApiResult
  >,
  'updateProduct' : ActorMethod<[SessionToken, UpdateProductInput], ApiResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];